### ISSUE TITLE
Two orientation

### ISSUE THREAD

**Issue by kiyeon-jo** [blueimp/JavaScript-Load-Image#103] opened 2020-04-24 02:54 UTC
Thank you always.

Your library reads only one orientation.

Of course, it is normal to have only one.

Unfortunately, if you rotate in the Microsoft Windows Photo Viewer, you will have two orientation records.

Can't you provide two pieces of information?

For your information, http://exif.regex.info/exif.cgi is showing two orientation information here.

**Comment by kiyeon-jo** [comment] 2020-04-24 02:58
Sample image with two orientation
![2020042211301336382](https://user-images.githubusercontent.com/14821472/80170231-79e0b100-8622-11ea-9cc2-fa4185db003c.jpg)

**Comment by kiyeon-jo** [comment] 2020-04-24 06:17
uploaded photo 
exif.get('Software') => "Microsoft Windows Photo Viewer 6.1.7600.16385"

**Comment by blueimp** [comment] 2020-04-28 16:31
Thanks for the report @kiyeon-jo.

I can confirm that your sample image does indeed contain two Orientation values.

Curious, I'm not aware of the EXIF standard supporting two values for the same tag number in the same Image File Directory.

[exiftool](https://exiftool.org/), which I consider as the standard tooling for EXIF, also only reports the last Orientation value when used on your sample image:
```sh
exiftool -Orientation image.jpg
```
```
Orientation                     : Horizontal (normal)
```

Technically it would be possible to collect all values for the same tag, but it's not clear how this data should be returned and consuming code would be surprised if the return value has a different type (e.g. an Array of two values instead of a single value).

Since the last Orientation value is also the correct one, I'm assuming that is expected behavior, so I'm inclined to close this ticket.

**Comment by flexilivre** [comment] 2020-04-29 12:27
Hi @blueimp ,

You are right, the problem I encounter seems to be a case of duplicate orientation values.

When I use the function [here](https://stackoverflow.com/questions/7584794/accessing-jpeg-exif-rotation-data-in-javascript-on-the-client-side/32490603#32490603) , I get the orientation that is right in my case. Would it be a good idea to use this code in your library in order to solve such case ?

Here the result from exiftool : 

![exif](https://user-images.githubusercontent.com/61969960/80595594-46889280-8a25-11ea-9dcd-8be4adf5ce73.jpg)

**Comment by blueimp** [comment] 2020-04-29 13:31
Thanks again for your report @flexilivre.
I'm now thinking that it might be valid to store a second Orientation value for the Thumbnail data.
I'll look into this and will likely release an update.

**Closed** 2020-04-29 19:45 UTC

**Comment by blueimp** [comment] 2020-04-29 19:56
I learned now that the Thumbnail directory (IFD1) can contain all Exif tags that appear in the main image meta data directory (IFD0), so storing them in the same map created override issues.

I've released a new version that stores the IFD1 (Thumbnail) data in a separate ExifMap:
https://github.com/blueimp/JavaScript-Load-Image/blob/master/README.md#exif-thumbnail

Thanks to this change, the thumbnail Orientation will not override the original image Orientation anymore and should fix the issues both of you encountered.

Here's how to retrieve both Orientation values:
```js
exif.get('Orientation')
exif.get('Thumbnail').get('Orientation')
```

Thanks again for your help @kiyeon-jo and @flexilivre!
